spring.application.name=gateway-service

server.port=8080
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka

jwt.secret=12345678901234567890123456789012
jwt.expiration=3600000

spring.data.redis.host=redis
spring.data.redis.port=6379
rate-limit.algorithm=sliding

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false // Don't include Java class information in the message.

logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN